In [66]:
import cv2
import os
import numpy
# Download a static FFmpeg build and add it to PATH.
%run util/load-ffmpeg.ipynb
print('Done!')

D:\Software\Anaconda\Library\bin\ffmpeg.exe
C:\Path_Program\ffmpeg.exe
Done!


In [67]:
for filename in os.listdir(os.getcwd() + "/data/videos"):
    dirs = os.getcwd() + "/data/images/" + filename[0:-4]
    try:
        os.makedirs(dirs)
    except IOError:
        print("dictionary " + dirs + " exist")
    # Do the depth data frame extraction
    !ffmpeg -i data/videos/video0.mp4 -r 10 -f image2 -map 0:v:1 {dirs}/image-%05d.jpeg

dictionary D:\work\yuntao\depth\workspace\depth_both_side\dataProcess/data/images/video0 exist
dictionary D:\work\yuntao\depth\workspace\depth_both_side\dataProcess/data/images/video1 exist


ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.2.1 (GCC) 20200122
  configuration: --disable-static --enable-shared --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil 

In [68]:
# Save depth images
for folder in os.listdir(os.getcwd() + "/data/images"):
    print(folder)
    for filename in os.listdir(os.getcwd() + "/data/images/" + folder):
        print(filename)
        img = cv2.imread('data/images/' + folder + "/" + filename,0)
        dirs = os.getcwd() + "/data/depth/" + folder
        try:
            os.makedirs(dirs)
        except IOError:
            print("dictionary " + dirs + " exist")
        numpy.savetxt(dirs + "/" + filename[0:-5] + ".csv", img, delimiter=",")

video0
image-00001.jpeg
dictionary D:\work\yuntao\depth\workspace\depth_both_side\dataProcess/data/depth/video0 exist
image-00002.jpeg
dictionary D:\work\yuntao\depth\workspace\depth_both_side\dataProcess/data/depth/video0 exist
image-00003.jpeg
dictionary D:\work\yuntao\depth\workspace\depth_both_side\dataProcess/data/depth/video0 exist
image-00004.jpeg
dictionary D:\work\yuntao\depth\workspace\depth_both_side\dataProcess/data/depth/video0 exist
image-00005.jpeg
dictionary D:\work\yuntao\depth\workspace\depth_both_side\dataProcess/data/depth/video0 exist
image-00006.jpeg
dictionary D:\work\yuntao\depth\workspace\depth_both_side\dataProcess/data/depth/video0 exist
image-00007.jpeg
dictionary D:\work\yuntao\depth\workspace\depth_both_side\dataProcess/data/depth/video0 exist
image-00008.jpeg
dictionary D:\work\yuntao\depth\workspace\depth_both_side\dataProcess/data/depth/video0 exist
image-00009.jpeg
dictionary D:\work\yuntao\depth\workspace\depth_both_side\dataProcess/data/depth/video0 

dictionary D:\work\yuntao\depth\workspace\depth_both_side\dataProcess/data/depth/video1 exist
image-00014.jpeg
dictionary D:\work\yuntao\depth\workspace\depth_both_side\dataProcess/data/depth/video1 exist
image-00015.jpeg
dictionary D:\work\yuntao\depth\workspace\depth_both_side\dataProcess/data/depth/video1 exist
image-00016.jpeg
dictionary D:\work\yuntao\depth\workspace\depth_both_side\dataProcess/data/depth/video1 exist
image-00017.jpeg
dictionary D:\work\yuntao\depth\workspace\depth_both_side\dataProcess/data/depth/video1 exist
image-00018.jpeg
dictionary D:\work\yuntao\depth\workspace\depth_both_side\dataProcess/data/depth/video1 exist
image-00019.jpeg
dictionary D:\work\yuntao\depth\workspace\depth_both_side\dataProcess/data/depth/video1 exist
image-00020.jpeg
dictionary D:\work\yuntao\depth\workspace\depth_both_side\dataProcess/data/depth/video1 exist
image-00021.jpeg
dictionary D:\work\yuntao\depth\workspace\depth_both_side\dataProcess/data/depth/video1 exist
image-00022.jpeg
d

In [69]:
# Save depth data as csv file
img = cv2.imread('data/images/video0/image-00001.jpeg',0)
name = "video0"
numpy.savetxt("data/depth/" + name[0:-5] + ".csv", img, delimiter=",")
rows,cols = img.shape
print(img)
for i in range(rows):
    print("row" + str(i))
    for j in range(cols):
        k = img[i,j]
        print(k, end=" ")

[[ 0  0  0 ... 19 19 19]
 [ 0  0  0 ... 19 19 19]
 [ 0  0  0 ... 19 19 19]
 ...
 [ 0  0  0 ... 20 20 20]
 [ 0  0  0 ... 20 20 20]
 [ 0  0  0 ... 20 20 20]]
row0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 2 2 2 12 0 1 5 1 4 14 16 16 18 8 0 225 215 227 225 217 226 220 27 23 21 22 28 19 19 22 22 15 36 34 34 32 29 5 22 22 18 23 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 22 21 19 19 21 23 21 18 18 18 18 19 19 20 20 20 19 19 19 19 19 19 19 19 row1
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 2 2 2 1 0 0 0 0 6 16 11 0 36 0 23 206 231 225 219 227 221 228 4 9 3 2 25 19 15 11 5 0 25 30 34 39 5 0 22 19 24 20 22 21 2

0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 0 0 0 0 2 2 1 0 21 20 0 8 16 214 222 215 222 226 218 206 0 1 0 3 10 8 5 2 29 39 35 39 3 2 25 21 22 14 24 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 24 23 22 20 18 16 14 13 16 16 17 18 19 21 21 22 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 row15
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 3 1 0 2 4 6 4 2 0 5 0 1 0 23 219 223 215 224 216 212 220 3 3 1 0 6 16 21 12 20 27 29 40 0 2 29 15 22 20 22 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 26 24 21 18 14 10 7 6 15 16 17 18 19 20 21 22 21 21 21 21 21 21 21 21 21 21 21 21 21

0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 7 8 13 3 202 0 0 25 13 0 24 15 217 208 207 208 207 207 207 204 207 205 0 0 1 0 0 0 39 39 42 39 1 0 21 20 18 20 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 19 16 8 1 0 0 0 0 1 3 2 0 1 10 18 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 19 19 19 19 19 19 19 19 row29
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 4 11 7 22 5 10 0 24 4 0 4 4 9 0 5 214 209 206 212 206 194 0 15 5 0 1 4 3 0 5 38 34 27 2 0 25 23 21 18 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 19 20 11 1 1 1 0 0 0 4 3 0 4 15 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 2

0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 5 12 4 0 18 19 19 1 0 4 0 15 128 152 144 146 152 32 24 7 31 19 17 5 19 19 0 0 21 23 124 145 21 23 22 16 20 24 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 19 19 19 19 19 19 19 19 row44
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 6 21 7 17 0 9 2 0 18 5 0 26 21 26 19 22 29 18 23 26 0 10 4 3 19 17 24 133 129 21 24 20 27 21 20 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 

0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 4 4 0 5 0 12 0 6 188 199 184 187 183 3 2 1 4 0 5 2 7 2 42 49 46 42 40 40 44 42 31 15 3 0 0 3 5 6 3 3 8 4 5 0 18 20 23 23 20 20 23 22 20 17 20 20 21 26 25 21 23 27 28 20 18 21 24 22 27 19 19 20 21 22 23 24 24 23 23 23 23 23 23 23 23 23 20 21 20 16 15 15 11 27 24 20 16 16 20 25 27 22 22 17 20 19 20 24 13 21 21 21 21 21 21 21 21 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 19 19 19 19 19 19 19 19 row60
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 7 0 8 0 7 0 0 6 0 1 0 5 1 23 21 8 0 0 29 2 16 12 21 0 3 41 48 37 59 44 43 47 43 42 42 44 47 47 44 42 39 43 42 26 8 0 0 28 19 16 14 14 11 6 4 6 0 6 4 2 4 1 0 4 8 0 4 15 22 23 23 17 24 23 23 22 21 21 20 20 21 21 21 21 21 21 21 21 23 18 21 23 18 20 24 19 22 21 21 21 21 20 20 21 16 15 24 16 7 17

0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 223 0 0 201 203 1 0 169 176 175 182 167 10 163 177 150 151 156 143 154 149 143 145 151 142 3 36 46 32 48 37 41 35 38 38 38 45 29 5 37 3 6 0 5 2 28 0 0 7 16 18 18 24 27 23 22 26 24 23 28 29 18 12 18 24 1 19 28 4 24 27 14 22 22 22 23 23 24 24 24 24 24 24 24 24 24 24 24 23 23 23 23 23 23 23 23 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 24 27 28 23 15 10 10 13 12 17 19 20 23 19 13 13 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 19 19 19 19 19 19 19 19 row75
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 15 191 217 0 15 0 168 174 173 2 180 188 2 9 149 146 141 141 146 140 156 133 7 37 36 46 45 29 37 39 39 39 32 30 5 15 0 2 2 7 0 4 0 16 5 17 24 30 25 19 23 26 25 27 27 25 25 28 28 21 18 21 19 0 22 23 2 20 23 16 22 22 22 23 23 24 24 24 24 24 24 24 24 24 24 24 23

0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 2 2 2 2 2 2 2 0 3 0 0 178 184 183 177 0 5 31 37 29 22 33 38 33 32 32 31 31 30 30 30 34 30 28 29 30 30 28 26 33 30 21 28 33 27 23 11 29 22 14 6 0 0 7 23 27 22 12 21 29 26 27 23 27 20 23 24 23 27 22 26 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 23 23 23 23 23 23 23 23 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 21 21 21 21 21 21 21 21 22 22 24 20 16 20 24 18 19 19 20 21 20 19 17 16 22 19 16 15 18 21 21 21 16 17 19 20 21 20 20 19 18 19 19 20 20 21 21 22 row90
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 2 2 2 2 2 2 2 5 0 7 0 9 178 182 174 0 3 19 38 32 29 29 34 32 32 32 31 31 30 30 29 34 27 26 33 35 30 27 30 27 29 26 32 27 17 23 28 0 5 16 26 29 27 27 31 30 24 4 9 27 24 19 17 27 19 24 22 22 20 18 28 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 23 23 23 23 23 23 23 23 22 22 22

0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 7 0 8 188 184 191 176 180 196 4 3 0 0 3 0 3 4 24 34 29 32 26 31 41 39 10 5 0 28 24 30 27 29 31 28 28 29 25 32 31 29 30 31 33 34 35 33 33 33 33 33 33 33 33 31 30 9 20 33 3 6 26 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 23 23 23 23 23 23 23 23 23 23 23 23 23 23 23 23 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 21 21 21 21 21 21 21 21 20 21 21 21 18 15 11 9 16 16 16 16 16 16 16 16 18 18 18 18 18 18 18 18 19 13 23 20 18 20 14 25 20 20 20 20 20 20 20 20 row104
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 5 0 0 0 0 0 2 4 0 2 184 194 190 183 178 196 194 3 11 0 2 8 0 0 5 28 37 30 26 25 27 7 7 23 28 32 24 30 30 30 30 30 30 30 30 31 31 31 32 32 33 33 33 33 33 33 33 33 33 33 33 33 31 0 3 25 24 1 25 26 26 26 25 25 24 24 24 24 24 24 24 24 24 24 24 23 23 23 23 23 23 23 23 23 23 23 23 23 2

0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 4 0 6 0 2 5 0 1 0 6 2 0 38 25 12 31 37 22 28 36 33 33 34 34 35 35 36 36 38 35 4 2 1 0 19 14 0 0 2 0 0 9 43 37 35 2 26 35 21 27 24 21 24 21 14 26 26 14 20 24 24 24 24 24 24 24 24 24 23 23 23 23 23 23 23 23 22 22 22 22 22 22 22 22 25 22 20 21 24 26 27 26 25 18 12 12 16 21 22 22 1 17 23 19 19 20 19 22 20 20 20 20 20 20 20 20 17 22 23 20 19 22 20 15 23 13 18 24 18 16 22 21 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 row120
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 194 11 0 6 0 5 0 5 0 0 0 0 0 0 0 0 0 0 3 0 1 5 0 2 38 37 28 28 42 32 31 33 36 33 37 32 27 38 34 0 0 0 4 0 4 1 23 28 1 4 5 0 5 7 5 37 34 14 20 31 27 28 28 20 27 22 25 18 1 6 22 22 22 27 27 22 22 26 26 21 23 24 25 26 26 25 24 23 24 24 24 23 23 22 22 22 22 22 22 22 22 22 22 22 25 0 0 22 21 18 21

0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 5 6 0 0 0 0 4 7 0 0 3 190 0 1 1 2 3 0 10 89 0 0 110 0 105 98 2 0 1 0 3 0 2 7 0 1 212 215 3 0 0 91 95 87 8 0 0 101 101 93 0 1 12 4 18 15 23 25 17 18 16 22 15 22 18 16 15 14 7 3 9 20 20 25 20 19 1 0 23 24 24 23 23 23 23 24 25 26 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 19 20 21 21 20 19 19 19 21 21 21 21 21 21 21 21 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 row148
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 15 0 96 0 1 2 1 1 0 190 3 0 0 185 10 0 2 99 6 0 6 7 0 8 0 0 0 9 0 3 0 219 0 5 215 0 0 3 93 90 108 0 12 98 94 100 91 3 6 0 6 0 0 0 4 0 8 10 18 18 27 25 18 16 22 24 17 8 3 6 15 22 24 7 3 24 25 21 21 22 23 24 24 24 24 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 21 21 21 21 21 21 21 21 2

0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 10 0 20 0 7 0 0 0 0 0 184 181 0 19 0 212 212 10 2 88 76 93 81 83 83 83 83 83 83 83 83 85 85 85 85 85 85 85 85 83 89 84 89 88 80 87 89 11 0 4 5 7 0 0 3 12 12 19 24 22 24 25 20 18 20 21 21 21 21 22 24 20 22 16 26 26 25 18 27 22 21 22 16 9 16 25 23 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 13 18 22 22 20 20 20 21 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 row164
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 6 0 12 0 0 90 9 1 11 0 0 0 182 3 170 191 0 2 177 1 81 88 86 79 83 83 83 83 83 83 83 83 84 84 84 84 84 84 84 84 85 92 87 86 86 79 80 83 69 9 10 4 2 3 16 26 10 10 17 24 23 25 27 22 17 22 25 23 19 17 21 25 16 8 17 21 23 15 21 20 26 21 6 0 10 20 19 18 21 21 21 21 21 21 21 21 2